#!/usr/bin/env python3
# Generates a clean index.html with no special chars, no patching artifacts

Q = [
  # ── FUNCTIONALITY (15%) ──
  ("Scenario: Your organisation wants external candidates to create a Workday account before submitting an application. The HR director wants to add a welcome message on the account page.\nWhere do you configure the Candidate Home Account requirement and introduction message?",["Edit Tenant Setup - HCM","Edit Tenant Setup - Recruiting","Maintain Recruiting Sources","Business Process Security Policy"],"Edit Tenant Setup - Recruiting","Candidate Home Account settings and the introduction message are both configured in Edit Tenant Setup - Recruiting (RA Ch. 1)."),
  ("Scenario: HR wants demographic information captured on a job application to automatically populate the new-hire record at time of hire, eliminating duplicate data entry.\nWhich setting in Edit Tenant Setup - Recruiting controls this?",["Enable Candidate Home Account","Copy Personal Information from Job Application","Enable Self-Scheduling","Recruiting Overload Count"],"Copy Personal Information from Job Application","Copy Personal Information from Job Application in Edit Tenant Setup - Recruiting carries candidate data into the hire transaction (RA Ch. 1)."),
  ("Scenario: Leadership wants Workday to flag recruiters who manage more open requisitions than a defined limit so managers can reassign work.\nWhich field in Edit Tenant Setup - Recruiting sets this threshold?",["Job Application Stage Order","Source Category Limit","Recruiting Overload Count","Max Headcount Threshold"],"Recruiting Overload Count","Recruiting Overload Count defines the maximum active requisitions per recruiter before an overload indicator appears (RA Ch. 1)."),
  ("Scenario: Recruiters report that delivered pipeline reports show recruiting stages in the wrong order, making dashboards hard to read.\nWhere is stage display order configured?",["Manage Business Process Definitions","Edit Tenant Setup - Recruiting, Job Application Stage Order","Maintain Recruiting Dispositions","Edit Job Posting Template"],"Edit Tenant Setup - Recruiting, Job Application Stage Order","The Job Application Stage Order section inside Edit Tenant Setup - Recruiting controls how stages are sequenced in delivered recruiting reports (RA Ch. 1)."),
  ("Scenario: The TA team wants a branded email automatically sent to every applicant upon submission, with the candidate name and job title as dynamic fields.\nWhich Workday object must be created?",["Recruiting Disposition","Candidate Communication Message Template","Job Posting Template","Notification Alert Rule"],"Candidate Communication Message Template","Candidate Communication Message Templates support dynamic merge fields and are used for automated candidate-facing emails (RA Ch. 6)."),
  ("Scenario: Your company wants to track whether applicants came from LinkedIn, a career fair, or an employee referral, grouped by category for reporting.\nWhat two objects must you create?",["Job Posting Locations and Job Profiles","Recruiting Source Categories and Recruiting Sources","Candidate Tags and Candidate Pools","Job Application Templates and Questionnaires"],"Recruiting Source Categories and Recruiting Sources","Recruiting Source Categories group Sources. Both must be configured in Maintain Recruiting Sources to track applicant origin (RA Ch. 5)."),
  ("Scenario: A recruiter reports that hybrid and remote options are not available on requisitions. The company wants to label roles as Onsite, Remote, or Hybrid consistently.\nWhich task creates these workplace arrangement options?",["Edit Job Posting Template","Maintain Job Requisition Remote Types","Configure Working Locations","Edit Tenant Setup - HCM"],"Maintain Job Requisition Remote Types","Maintain Job Requisition Remote Types defines the allowable workplace arrangements selectable on a requisition (RA Ch. 2)."),
  ("Scenario: A candidate voluntarily decides to withdraw their application. Compliance wants this recorded differently from a recruiter-initiated rejection and wants candidates to trigger it themselves.\nWhich disposition option enables candidate-initiated withdrawal?",["Requires Approval","Candidate Withdrawal","Disposition Remaining Jobs","Auto-Advance"],"Candidate Withdrawal","Enabling Candidate Withdrawal on a recruiting disposition allows the candidate to self-select the withdrawal outcome (RA Ch. 9)."),

  # ── BUSINESS PROCESSES (30%) ──
  ("Scenario: A junior admin watched the Job Application BP fire for the first time after a candidate submitted. They ask what the initiation step does.\nWhat is the purpose of the initiation step in the Job Application business process?",["Routes the application to the hiring manager","Fires automatically on submission and launches the dynamic BP flow","Sends the offer letter to the candidate","Triggers the background check subprocess"],"Fires automatically on submission and launches the dynamic BP flow","The initiation step fires when a candidate submits an application and starts the dynamic Job Application BP. It cannot be configured or moved (RA Ch. 9)."),
  ("Scenario: Recruiters need candidates to complete an online assessment and a phone screen at the same time. Currently the BP runs these one after another, causing delays.\nWhich section of the Job Application BP supports simultaneous execution?",["Initial Step","Possible Dispositions","Possible Next Steps","Possible Parallel Steps"],"Possible Parallel Steps","Possible Parallel Steps allow multiple recruiting activities to run concurrently within the Job Application BP (RA Ch. 9)."),
  ("Scenario: Your company requires a structured phone screening with a pass/fail outcome recorded in Workday before any candidate advances to interviews.\nWhich subprocess is designed for this evaluation stage?",["Review","Screen","Assessment","Interview"],"Screen","The Screen subprocess captures structured evaluations such as phone screens with pass/fail outcomes (RA Ch. 8)."),
  ("Scenario: A senior executive search requires a third-party psychometric test. Results must return to Workday before interviews are scheduled.\nWhich subprocess integrates with external testing vendors?",["Screen","Assessment","Reference Check","Employment Agreement"],"Assessment","The Assessment subprocess integrates with third-party testing vendors and stores results on the job application record (RA Ch. 8)."),
  ("Scenario: A compliance officer finds that background checks are starting before offers are accepted. The team needs a sequencing control in the business process.\nWhat configuration ensures Background Check cannot start until the offer step is complete?",["Security group restriction on Background Check step","Condition rule on the Background Check step evaluating offer status","Recruiting disposition assignment","Job posting template restriction"],"Condition rule on the Background Check step evaluating offer status","A condition rule on the Background Check subprocess evaluates whether the offer was accepted before allowing the step to proceed (RA Ch. 8)."),
  ("Scenario: The Interview subprocess fires for all requisitions but should only run for external hires, not internal transfers.\nHow should you configure the BP to skip Interview for internal transfers?",["Delete the Interview subprocess from the BP","Add a condition rule on the Interview step evaluating requisition type","Create a separate business process for internal requisitions","Change the security group on the Interview step"],"Add a condition rule on the Interview step evaluating requisition type","A condition rule on the Interview subprocess evaluates requisition type and skips the step for internal transfer applications (RA Ch. 8)."),
  ("Scenario: HR Operations needs a final approval before any candidate is converted to a pre-hire. An analyst asks what the Ready for Hire subprocess does.\nWhat is the primary purpose of Ready for Hire?",["Triggers the background check integration","Marks the candidate as approved for conversion to pre-hire or worker","Sends the offer letter","Automatically closes the requisition"],"Marks the candidate as approved for conversion to pre-hire or worker","Ready for Hire is the final subprocess in the Job Application BP. It approves the candidate for conversion to a pre-hire record (RA Ch. 8)."),
  ("Scenario: An HR admin is configuring the Job Application BP and receives a validation error saying a Completion step is missing.\nWhich subprocess fulfils the required Completion step?",["Offer","Interview","Hire","Ready for Hire"],"Ready for Hire","Ready for Hire acts as the Completion step of the Job Application business process and is required for the BP to be valid (RA Ch. 9)."),
  ("Scenario: After one candidate accepts an offer on a single-headcount requisition, the TA director wants all remaining applicants automatically declined.\nWhich configuration enables this?",["Automatic Stage Routing rule","Exit condition rule on the Offer step","Decline Remaining Candidates step in the Ready for Hire subprocess","Completion condition rule on the Hire event"],"Decline Remaining Candidates step in the Ready for Hire subprocess","Adding Decline Remaining Candidates to Ready for Hire automatically dispositions all other applicants once a hire is finalised (RA Ch. 9)."),
  ("Scenario: Candidates need to self-schedule their own phone screening appointments from a calendar link, without contacting a recruiter.\nWhich business process step enables candidate self-scheduling?",["Schedule Interview","Candidate Endorsement","Candidate Self-Schedule Event","Manage Candidate Process"],"Candidate Self-Schedule Event","The Candidate Self-Schedule Event step allows candidates to select and manage their own appointment slots (RA Ch. 8)."),
  ("Scenario: References must be collected for final-round candidates before an offer is extended. The current BP allows offers without reference check completion.\nWhich subprocess captures formal reference information?",["Assessment","Screen","Reference Check","Employment Agreement"],"Reference Check","The Reference Check subprocess facilitates collection of formal reference information before the offer stage (RA Ch. 8)."),
  ("Scenario: A union hiring process requires candidates to sign an employment agreement before a background check can begin. HR needs this enforced in the BP.\nWhich subprocess captures the candidate-signed employment contract?",["Offer","Reference Check","Employment Agreement","Background Check"],"Employment Agreement","The Employment Agreement subprocess captures the signed contract and can be sequenced before Background Check (RA Ch. 8)."),
  ("Scenario: A BP step requires a senior director to formally approve before a candidate advances past screening. This approval is configurable per-requisition.\nWhich step type is used for formal approvals in the Job Application BP?",["To Do","Approval","Action","Notification"],"Approval","The Approval step requires a designated person or group to formally approve before the BP proceeds (HCMCA Ch. 9)."),
  ("Scenario: An HR business partner must be notified when a candidate reaches Ready for Hire but does not need to take any action.\nWhich BP step type should be used?",["Approval","To Do","Notification","Action"],"Notification","A Notification step sends an alert to recipients without requiring any action or approval (HCMCA Ch. 9)."),
  ("Scenario: Once a candidate is declined and the disposition fires, the action cannot be reversed. A junior admin asks which disposition option allows it to be undone.\nWhich disposition configuration allows a disposition to be rescinded?",["Candidate Withdrawal enabled","Disposition Remaining Jobs enabled","Allow Rescind enabled","Auto-Advance enabled"],"Allow Rescind enabled","Enabling Allow Rescind on a recruiting disposition lets authorised users reverse a previously applied disposition (RA Ch. 9)."),

  # ── REQUISITIONS AND COMPONENTS (25%) ──
  ("Scenario: Recruiters manually add the same five questions every time a Software Engineer requisition opens. They want these to pre-populate automatically.\nWhich object defines the questions on a candidate-facing application form?",["Job Posting Template","Job Application Template","Recruiting Source","Supplemental Questionnaire"],"Job Application Template","A Job Application Template defines which questions and sections appear on the candidate-facing application form (RA Ch. 2)."),
  ("Scenario: A Finance department requisition should auto-populate Cost Center and Company based on the supervisory org without manual input.\nWhat feature defaults these values onto requisitions?",["Job Posting Template","Condition Rules on the Job Requisition","Evergreen Requisition defaults","Ad Hoc Role"],"Condition Rules on the Job Requisition","Condition rules on the job requisition evaluate org criteria and automatically default values like Cost Center and Company (RA Chs. 3, 4)."),
  ("Scenario: A recruiter wants to eliminate scheduling emails by letting candidates pick their own interview slots from the career site.\nWhat must be added to the job requisition to enable this?",["Job Posting Location","Self-Scheduling Calendar","Ad Hoc Interviewer Role","Supplemental Questionnaire"],"Self-Scheduling Calendar","A Self-Scheduling Calendar attached to the job requisition exposes available slots to candidates on the career site (RA Ch. 3)."),
  ("Scenario: The company continuously hires hourly warehouse staff. The TA director wants a single always-open pipeline collecting applicants until needed.\nWhich requisition type supports this?",["Standard Job Requisition","Evergreen Requisition","Confidential Requisition","Pipeline Requisition"],"Evergreen Requisition","Evergreen Requisitions are designed for continuous talent pipelines with no defined headcount or close date (RA Chs. 3, 10)."),
  ("Scenario: A questionnaire has knockout questions that auto-disqualify applicants below minimum requirements. A separate questionnaire collects preferences. What is the difference between the two?\nWhat is the primary functional difference between a primary and supplemental questionnaire?",["Primary questionnaires can be reused; supplemental cannot","Primary questionnaires support knockout disqualification logic; supplemental questionnaires only collect information","Primary questionnaires are for internal candidates; supplemental for external","Primary questionnaires are mandatory; supplemental are optional"],"Primary questionnaires support knockout disqualification logic; supplemental questionnaires only collect information","Primary questionnaires support knockout logic that can auto-disqualify. Supplemental questionnaires gather extra information without disqualification (RA Chs. 2, 8)."),
  ("Scenario: A requisition was submitted with incorrect compensation data. No candidates have applied yet and the hiring manager wants to correct it.\nWhat action should be taken?",["Cancel and recreate the requisition","Edit the Job Requisition directly using the Edit Job Requisition action","Modify the job profile linked to the requisition","Submit a new offer to override the compensation"],"Edit the Job Requisition directly using the Edit Job Requisition action","The Edit Job Requisition action allows authorised users to modify fields including compensation (RA Ch. 3)."),
  ("Scenario: Recruiters need to post an open role to three specific cities on the career site and let applicants indicate their preferred location.\nWhich object must be created to make cities selectable on a requisition?",["Recruiting Sources","Job Posting Locations","Self-Scheduling Calendars","Candidate Tags"],"Job Posting Locations","Job Posting Locations define the specific sites or cities that can be associated with a requisition and shown to candidates (RA Ch. 2)."),
  ("Scenario: Hiring managers complain that the job description on new requisitions must be typed from scratch each time. They want it to pull from the job profile.\nWhich setting enables this auto-population?",["Enable Org Defaults","Default Job Description from Job Profile","Job Application Template","Job Posting Template Content"],"Default Job Description from Job Profile","Enabling Default Job Description from Job Profile causes the job profile description to pre-populate on new requisitions (RA Ch. 2)."),
  ("Scenario: Organisation assignments are configured in supervisory orgs. HR wants Company, Cost Center, and Region to automatically default onto new requisitions.\nWhich setting enables this?",["Enable Job Requisitions for Job Management","Default Job Description from Job Profile","Enable Organisation Defaults on Create Job Requisition","Enable Evergreen Requisition Defaults"],"Enable Organisation Defaults on Create Job Requisition","Enable Organisation Defaults on Create Job Requisition copies org assignment values from the supervisory org onto new requisitions (RA Ch. 3)."),
  ("Scenario: Recruiters want to move multiple candidates from an evergreen pipeline into a specific open standard requisition for immediate consideration.\nWhich action transfers candidates from evergreen to standard?",["Clone the evergreen as a standard requisition","Move to Job Requisition action on the candidate record","Modify the evergreen requisition type to standard","Re-apply the candidates manually"],"Move to Job Requisition action on the candidate record","The Move to Job Requisition action on the evergreen candidate record transfers them to a designated standard requisition (RA Ch. 10)."),
  ("Scenario: Two evergreen requisitions exist for the same role family. A recruiter tries to move a candidate between them but gets an error.\nWhat must both evergreen requisitions share to allow candidate transfers?",["The same hiring manager","The same supervisory organisation","At least one common location","At least one common job profile"],"At least one common job profile","Candidates can only be transferred between evergreen requisitions that share at least one common job profile (RA Ch. 10)."),
  ("Scenario: An organisation wants assessments for a specific job family to auto-populate on any new requisition for that family, without manual selection.\nWhich configuration supports automated assessment defaulting?",["Add assessments directly to Job Profiles","Configure competencies on positions","Create a condition rule and assign it in Maintain Job Requisition Assessment Defaults","Add assessments to the Interview subprocess"],"Create a condition rule and assign it in Maintain Job Requisition Assessment Defaults","Condition rules combined with Maintain Job Requisition Assessment Defaults automate assessment population (RA Chs. 2, 8)."),

  # ── JOB APPLICANTS (20%) ──
  ("Scenario: An internal employee searches Workday for open positions in Operations and wants to apply without leaving the HR portal.\nWhich delivered feature allows internal employees to search and apply for internal postings?",["External Career Site","Browse Jobs on the Internal Career Site","Recruiting Dashboard","Candidate Home Account"],"Browse Jobs on the Internal Career Site","Browse Jobs is the delivered report on the internal career site that enables employees to search, filter, and apply to internal postings (RA Chs. 4, 5)."),
  ("Scenario: HR wants employees to automatically receive email alerts when new roles matching their skills are posted, without checking the career site daily.\nWhich feature delivers these notifications?",["Recruiting Source Notification","Job Alerts","Business Process Notification","Candidate Message Template"],"Job Alerts","Job Alerts on the internal career site send automated emails to employees when new matching roles are posted (RA Ch. 5)."),
  ("Scenario: A global company needs to configure its external career site to display gender identity options for German applicants only.\nWhich configuration controls country-specific data collection?",["Configure Optional Fields in Tenant Setup","Maintain Localization Settings","Edit Tenant Setup - Recruiting","Maintain Candidate Tags"],"Maintain Localization Settings","Maintain Localization Settings controls country-specific candidate information fields and requirements on the career site (RA Chs. 5, 6)."),
  ("Scenario: A candidate applied 3 months ago, was not selected, and now has no active application. The TA team wants to track this person for future roles.\nWhich candidate status describes a person with no active application but tracked for future consideration?",["Active Candidate","Prospect","Pre-Hire","Worker"],"Prospect","A Prospect is a person of interest who has no active job application but is tracked for future opportunities (RA Ch. 6)."),
  ("Scenario: A recruiter converted a candidate to a pre-hire. HR asks what the functional difference is between a pre-hire and a worker.\nWhat distinguishes a pre-hire record from a worker record?",["A pre-hire has compensation data; a worker does not","A pre-hire has not completed the hire transaction; a worker has","A pre-hire has a Workday login; a worker does not","There is no difference"],"A pre-hire has not completed the hire transaction; a worker has","A pre-hire record is created after selection but before the Hire BP is completed. A worker record is created when the Hire BP is finalised (RA Ch. 6)."),
  ("Scenario: The marketing team wants a differently branded external career site from the engineering team - separate logos and job filters for each.\nHow many external career sites can be configured in a single Workday tenant?",["Only one external career site per tenant","Up to two external career sites","Up to five external career sites","An unlimited number of external career sites"],"An unlimited number of external career sites","Workday supports multiple external career sites within a single tenant, each with its own branding and filters (RA Ch. 5)."),
  ("Scenario: You updated a posted requisition but internal candidates still see old information on the career site. No error messages appear.\nWhat must you do to make the updates visible?",["Regenerate the Job Application Template","Run the Refresh Recruiting Data process","Unpost and repost the requisition","Edit the internal career site configuration"],"Unpost and repost the requisition","Changes made to a posted requisition are not reflected on the career site until it is unposted and reposted (RA Ch. 4)."),
  ("Scenario: A recruiter wants to maintain a shortlist of high-potential candidates not attached to any current requisition for future outreach.\nWhich Workday object stores candidates outside of an active application?",["Job Alert","Candidate Pool","Candidate Tag","Evergreen Requisition"],"Candidate Pool","Candidate Pools allow recruiters to group and manage candidates for future roles independent of any active requisition (RA Ch. 6)."),
  ("Scenario: An external career site is being configured for Canada and the UK. The client wants country-specific legal disclaimers based on applicant location.\nWhich configuration option supports location-based display variations?",["Create separate career sites per country","Identify country or location specific configuration options within the career site settings","Configure recruiting sources per country","Add condition rules to the Job Application Template"],"Identify country or location specific configuration options within the career site settings","External career sites support country or location-specific configuration options including legal text and job alert settings (RA Chs. 5, 6)."),
  ("Scenario: A recruiter moved candidates from an evergreen to a standard requisition. The openings were later paused and the team wants those candidates back in the evergreen pipeline.\nWhich action returns them to the evergreen?",["Move to a candidate pool and recreate the evergreen","Delete and re-add them to the evergreen","Move candidates back using the Move to Evergreen Requisition action","Convert to prospects and re-attach to the evergreen"],"Move candidates back using the Move to Evergreen Requisition action","Candidates can be returned to the original evergreen requisition using the Move to Evergreen Requisition action (RA Ch. 10)."),

  # ── SECURITY (10%) ──
  ("Scenario: A company recruits by geography. West Coast recruiters should only see requisitions for California and Oregon, not other regions.\nWhich object should the Recruiting role be enabled for to support geography-based access?",["Supervisory Organisation","Recruiting Agency","Job Requisition","Location Hierarchy"],"Location Hierarchy","Enabling the Recruiting role for Location Hierarchy restricts recruiter access to only the locations within their defined geographic scope (RA Chs. 3, 7)."),
  ("Scenario: A confidential executive search must be visible only to the CHRO, CFO, and one named recruiter. A standard security group would expose it to the whole TA team.\nWhich feature grants targeted access to specific individuals on a single requisition?",["Create a dedicated restricted security group","Assign Ad Hoc Roles on the requisition","Modify the Recruiter domain security policy","Add a condition rule to hide the requisition"],"Assign Ad Hoc Roles on the requisition","Ad Hoc Roles on a job requisition grant access to named individuals for that requisition without affecting global security group assignments (RA Ch. 3)."),
  ("Scenario: An HR analyst needs to understand the difference between a domain security policy and a business process security policy for Recruiting access.\nWhat is the primary distinction between these two policy types?",["Domain policies control data and task access; BP policies control who acts on BP steps","Domain policies apply to external users; BP policies apply to internal users","Domain policies are per-requisition; BP policies are global","There is no difference - they are configured in the same place"],"Domain policies control data and task access; BP policies control who acts on BP steps","Domain security policies govern read/write access to data and tasks. BP security policies determine who can initiate, approve, or act on specific BP steps (HCMCA Ch. 2)."),
  ("Scenario: You need to create an assignable role so specific users can be granted the Recruiter role on individual requisitions at runtime rather than being permanent group members.\nWhat is the correct configuration sequence?",["Create a domain security policy, then assign users","Create an assignable role, create a security group referencing it, configure domain and BP policies","Create a user-based security group and add recruiters","Assign the role directly in Edit Tenant Setup - Recruiting"],"Create an assignable role, create a security group referencing it, configure domain and BP policies","Assignable roles require creating the role first, then a security group that references it, then configuring domain and BP security policies (RA Ch. 7, HCMCA Ch. 2)."),
  ("Scenario: After configuring new domain and BP security policies for the Recruiting module, the changes are not visible when testing.\nWhat must be done for Workday security policy changes to take effect?",["Restart the Workday tenant","Run Activate Pending Security Policy Changes","Re-assign all affected security groups","Re-run the impacted business processes"],"Run Activate Pending Security Policy Changes","All Workday security policy changes require running Activate Pending Security Policy Changes before they are enforced (HCMCA Ch. 2)."),
]

def js_str(s):
    """Convert Python string to safe JS single-quoted string"""
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "\\'")
    s = s.replace('\n', '\\n')
    return "'" + s + "'"

def js_arr(items):
    return '[' + ','.join(js_str(i) for i in items) + ']'

pool_js = 'recruiting: [\n'
for qt, opts, ans, expl in Q:
    pool_js += '      {question_text:' + js_str(qt)
    pool_js += ',options:' + js_arr(opts)
    pool_js += ',correct_answer:' + js_str(ans)
    pool_js += ',explanation:' + js_str(expl) + '},\n'
pool_js += '    ]'

print("Pool JS generated:", len(pool_js), "chars")
print("Questions:", len(Q))
print("First question preview:", pool_js[:200])

# Save pool for use in build
with open('/tmp/pool.js', 'w', encoding='utf-8') as f:
    f.write(pool_js)
print("Saved to /tmp/pool.js")
